version: '3.4'

services:
  libapp.webapi:
    image: ${DOCKER_REGISTRY-}libapp
    build:
      context: .
      dockerfile: API/src/LibApp.WebApi/Dockerfile
    ports:
      - 5237:80
  libapp.webui:
    image: ${DOCKER_REGISTRY-}libappui
    build:
      context: .
      dockerfile: UI/Dockerfile
    ports:
      - 4200:80